In [1]:
import numpy as np

In [2]:
np.array((3,4))

array([3, 4])

In [3]:
np.empty((3,4))

array([[4.64081551e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.03977794e-312, 1.01855798e-312, 1.23075756e-312,
        1.06099790e-312],
       [1.08221785e-312, 9.76118064e-313, 1.10343781e-312,
        1.90979621e-312]])

In [4]:


np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr1= np.eye(3)

In [8]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr1*5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [10]:
arr1+5

array([[6., 5., 5.],
       [5., 6., 5.],
       [5., 5., 6.]])

In [11]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
np.eye(3, dtype = str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [13]:
import pandas as pd

In [14]:
pd.DataFrame(arr1)# Concerting Array in data frame

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [15]:
import random

In [16]:
random.choice((1,2,3,4,5,6))

1

In [17]:
random.choice((1,2,3,4,5,6))

6

In [18]:
random.choice((1,2,3,4,5,6))

6

In [19]:
random.choice((1,2,3,4,5,6))

6

In [20]:
random.choice((1,2,3,4,5,6))

6

In [21]:
random.choice((1,2,3,4,5,6))

3

In [22]:
random.choice((1,2,3,4,5,6,"hi"))

5

In [23]:
random.choice((1,2,3,4,5,6,"hello"))

4

In [24]:
random.choice('Sumit')

'S'

In [25]:
random.choice('Sumit')

'u'

In [26]:
random.randrange(1, 1000)

457

In [27]:
random.randrange(1, 1000)

906

In [28]:
random.random() # a random generated a number b/w 0 & 1 (o included ,1 excluded)

0.8595509179536015

In [29]:
random.random()

0.2047333975875809

In [30]:
lis = [1,2,3,4,5,6,7,6,8,6]
random.shuffle(lis)

In [31]:
lis

[8, 6, 5, 2, 1, 3, 6, 7, 6, 4]

In [34]:
random.uniform(7,14) # number b/w 7, 14

7.007020889295757

In [33]:
random.uniform(7,14)

8.912657284416648

In [36]:
#Numpy 

np.random.rand(2,3)

array([[0.5615284 , 0.88653098, 0.45270759],
       [0.42189978, 0.1932554 , 0.88255452]])

In [37]:
np.random.randn(2,3)

array([[-0.25813843, -0.46763066, -1.72737322],
       [ 1.13971695,  0.21494536, -0.13437271]])

In [38]:
np.random.random_sample()

0.796320475500212

In [39]:
np.random.randint(1,5, size = (3,4))

array([[2, 3, 1, 4],
       [2, 4, 3, 3],
       [3, 3, 4, 2]])

In [40]:
arr2 = np.random.randint(1,5, size = (3,4))

In [41]:
arr2

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [42]:
arr2.size

12

In [43]:
arr2.shape

(3, 4)

In [44]:
arr2.ndim

2

In [45]:
arr2.reshape(2,6)

array([[3, 3, 1, 1, 1, 3],
       [2, 2, 2, 4, 2, 2]])

In [49]:
arr2.reshape(2,1) # arr2 size is 12 hence it can accomdate in (2,6) or (6,2) or (4,3) or (12) or (12,)size , means multiple of array size

ValueError: cannot reshape array of size 12 into shape (2,1)

In [47]:
arr2.reshape(2,8)

ValueError: cannot reshape array of size 12 into shape (2,8)

In [48]:
arr2.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [50]:
arr2.reshape(6,2)

array([[3, 3],
       [1, 1],
       [1, 3],
       [2, 2],
       [2, 4],
       [2, 2]])

In [51]:
arr2.reshape(12,)

array([3, 3, 1, 1, 1, 3, 2, 2, 2, 4, 2, 2])

In [53]:
arr2.reshape(12)

array([3, 3, 1, 1, 1, 3, 2, 2, 2, 4, 2, 2])

In [54]:
arr2.reshape(4,3)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 2],
       [4, 2, 2]])

In [55]:
arr2.reshape(4, -1)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 2],
       [4, 2, 2]])

In [56]:
arr2.reshape(4, -100)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 2],
       [4, 2, 2]])

In [ ]:
arr2.reshape(3, -1)

In [58]:
arr2.reshape(-1,5)

ValueError: cannot reshape array of size 12 into shape (5)

In [59]:
arr2.reshape(-3, -4)

ValueError: can only specify one unknown dimension

In [60]:
arr2.reshape(-3, 4)

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [61]:
arr2.reshape(3, 4).base

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [62]:
arr2.reshape(3, 4)

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [63]:
arr2.reshape(12, 1).base

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [64]:
arr2.reshape(12, 1)

array([[3],
       [3],
       [1],
       [1],
       [1],
       [3],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2]])

In [65]:
arr2.reshape(12, 1).base

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [66]:
arr2

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [2, 4, 2, 2]])

In [68]:
arr2.reshape(2,2,3)

array([[[3, 3, 1],
        [1, 1, 3]],

       [[2, 2, 2],
        [4, 2, 2]]])

In [71]:
arr2.reshape(2,3,2)

array([[[3, 3],
        [1, 1],
        [1, 3]],

       [[2, 2],
        [2, 4],
        [2, 2]]])

In [72]:
arr2.reshape(1,2,2,3)

array([[[[3, 3, 1],
         [1, 1, 3]],

        [[2, 2, 2],
         [4, 2, 2]]]])

In [73]:
arr2.reshape(4,3,1)

array([[[3],
        [3],
        [1]],

       [[1],
        [1],
        [3]],

       [[2],
        [2],
        [2]],

       [[4],
        [2],
        [2]]])

In [75]:
arr1.reshape(1,1,1,1,1,1,1,1,1,1,1,2,2,3)

ValueError: cannot reshape array of size 9 into shape (1,1,1,1,1,1,1,1,1,1,1,2,2,3)

In [76]:
lis =[1,2,3,4]
lis

[1, 2, 3, 4]

In [77]:
arr3 = np.array(lis)

In [78]:
arr3

array([1, 2, 3, 4])

In [79]:
arr3.ndim

1

In [81]:
arr3 = np.array(([2,3],[4,5]))

In [82]:
arr3

array([[2, 3],
       [4, 5]])

In [83]:
arr3.ndim

2

In [85]:
arr4 = np.zeros((3,4))

In [86]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
arr4.ndim

2

In [88]:
arr4 = np.zeros((1,3,4))# matrxi of 3,4 with 1 extra dimension

In [89]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [90]:
arr4.ndim

3

In [91]:
arr5 = np.zeros((1,1,3,4))
arr5

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [92]:
arr5.ndim

4

In [93]:
arr5.shape

(1, 1, 3, 4)

In [94]:
arr6 = np.zeros((1,3,4))
arr6

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [95]:
arr6.ndim

3

In [96]:
arr6 = np.zeros((2,3,4))
arr6

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [97]:
arr6 = np.zeros((4,3,4))
arr6

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [98]:
arr7 = np.zeros((-1,3,4))
arr7

ValueError: negative dimensions are not allowed

In [99]:
arr7 = np.zeros((0,3,4))
arr7

array([], shape=(0, 3, 4), dtype=float64)

In [102]:
arr8 = np.random.randint(1,10,(5,6))
arr8

array([[5, 9, 5, 2, 9, 9],
       [6, 4, 6, 9, 8, 7],
       [3, 1, 3, 5, 1, 1],
       [5, 3, 5, 3, 8, 7],
       [4, 7, 9, 6, 4, 6]])

In [103]:
arr8>1

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [104]:
arr8[arr8 > 5]

array([9, 9, 9, 6, 6, 9, 8, 7, 8, 7, 7, 9, 6, 6])

In [106]:
arr8[0]

array([5, 9, 5, 2, 9, 9])

In [108]:
arr8[0 , [1,3]]

array([9, 2])

In [109]:
arr8[1 , [1,4]]

array([4, 8])

In [110]:
arr8[2:4, [2,3]]

array([[3, 5],
       [5, 3]])

In [111]:
arr8

array([[5, 9, 5, 2, 9, 9],
       [6, 4, 6, 9, 8, 7],
       [3, 1, 3, 5, 1, 1],
       [5, 3, 5, 3, 8, 7],
       [4, 7, 9, 6, 4, 6]])

In [112]:
arr8[2:4]

array([[3, 1, 3, 5, 1, 1],
       [5, 3, 5, 3, 8, 7]])

In [113]:
arr8[2:7]

array([[3, 1, 3, 5, 1, 1],
       [5, 3, 5, 3, 8, 7],
       [4, 7, 9, 6, 4, 6]])

In [114]:
arr8[2:4, [0,2]]

array([[3, 3],
       [5, 5]])

In [115]:
arr8[2:4, 0:2] # slicing of  array

array([[3, 1],
       [5, 3]])

In [127]:
arr9 = np.random.randint(1,3,(4,3))
arr9

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [128]:
arr10 = np.random.randint(1,3,(4,3))
arr10

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [129]:
arr9 + arr10

array([[3, 3, 4],
       [2, 3, 3],
       [3, 2, 2],
       [4, 4, 4]])

In [130]:
arr9 * arr10

array([[2, 2, 4],
       [1, 2, 2],
       [2, 1, 1],
       [4, 4, 4]])

In [131]:
arr9 @ arr10

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [132]:
arr11 = np.random.randint(1,3,(3,3))
arr11

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [133]:
arr10 @ arr11 # matrix multiplication

array([[ 8,  8,  8],
       [ 8,  8,  8],
       [ 5,  5,  5],
       [10, 10, 10]])

In [135]:
arr9 / arr10

array([[2. , 0.5, 1. ],
       [1. , 0.5, 0.5],
       [2. , 1. , 1. ],
       [1. , 1. , 1. ]])

In [136]:
arr11 / 0

/tmp/ipykernel_110/1768603788.py:1: RuntimeWarning: divide by zero encountered in divide
  arr11 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [137]:
# Broad casting

In [146]:
arr12 = np.zeros((1,2,3))

In [147]:
arr12

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [151]:
a = np.array([1,2,3])

In [152]:
a 

array([1, 2, 3])

In [153]:
arr12 + a


array([[[1., 2., 3.],
        [1., 2., 3.]]])

In [160]:
b = np.array([1,2,3,4])

In [162]:
b.T

array([1, 2, 3, 4])

In [156]:
arr12 + b

ValueError: operands could not be broadcast together with shapes (1,2,3) (4,) 

In [157]:
b.T


array([1, 2, 3, 4])

In [158]:
b

array([1, 2, 3, 4])

In [159]:
a.T

array([1, 2, 3])

In [163]:
arr12

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [164]:
arr12.T

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [165]:
arr12.T + b

array([[[1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.]]])

In [166]:
np.sqrt(arr12)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [167]:
np.log10(arr12)

/tmp/ipykernel_110/155814875.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr12)


array([[[-inf, -inf, -inf],
        [-inf, -inf, -inf]]])

In [168]:
np.exp(arr12)

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [169]:
np.min(arr12)

0.0

In [170]:
arr12.flatten

<function ndarray.flatten>

In [171]:
#expand_dims >> exands the array by inserting a new dimesnion

In [174]:
arr13 = np.array([[1,2,3],[4,5,6]])

In [175]:
arr13

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
np.sum(arr13)

21

In [178]:
np.sum(arr13, axis=0)

array([5, 7, 9])

In [179]:
np.sum(arr13, axis=1)

array([ 6, 15])

In [181]:
arr14 = np.array([1,2,3,4])
arr14

array([1, 2, 3, 4])

In [182]:
arr14

array([1, 2, 3, 4])

In [183]:
arr14.ndim

1

In [185]:
arr15 = np.expand_dims(arr14, axis =0 )
arr15

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [187]:
arr16 = np.expand_dims(arr15, axis =0 )
arr16

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [188]:
arr17 = np.expand_dims(arr16, axis =0 )
arr17

array([[[[[[1, 2, 3],
           [4, 5, 6]]]]]])

In [189]:
arr17 = np.expand_dims(arr16, axis = 1 )
arr17

array([[[[[[1, 2, 3],
           [4, 5, 6]]]]]])

In [190]:
arr18 = np.expand_dims(arr, axis = 1 )
arr18

array([[[1, 2, 3]],

       [[4, 5, 6]]])