In [1]:
import numpy as np

In [3]:
a =np.array([[1,2],[3,4]])

#arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
np.repeat(a , 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [6]:
data

NameError: name 'data' is not defined

In [7]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
np.roll(a,-2)

array([[3, 4],
       [1, 2]])

In [9]:
np.roll(a,-3)

array([[4, 1],
       [2, 3]])

In [12]:
b =np.array([[[1,2],[3,4],[5,6]]])

In [13]:
b

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [14]:
np.roll(b,-2)

array([[[3, 4],
        [5, 6],
        [1, 2]]])

In [15]:
np.roll(b,1,axis=1)#axis=1:column wise

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [81]:
#Binary opeartion on array
arr1 = np.random.randint(1, 10,(3,4))
arr2 = np.random.randint(1, 10,(3,4))

In [19]:
arr1

array([[6, 1, 6, 7],
       [7, 6, 6, 5],
       [8, 2, 7, 1]])

In [20]:
arr2

array([[3, 5, 3, 4],
       [1, 6, 5, 5],
       [6, 2, 2, 2]])

In [21]:
arr1+arr2

array([[ 9,  6,  9, 11],
       [ 8, 12, 11, 10],
       [14,  4,  9,  3]])

In [22]:
arr1*arr2

array([[18,  5, 18, 28],
       [ 7, 36, 30, 25],
       [48,  4, 14,  2]])

In [23]:
arr1**arr2

array([[   216,      1,    216,   2401],
       [     7,  46656,   7776,   3125],
       [262144,      4,     49,      1]])

In [24]:
arr1>arr2

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [25]:
~arr1

array([[-7, -2, -7, -8],
       [-8, -7, -7, -6],
       [-9, -3, -8, -2]])

In [26]:
arr1

array([[6, 1, 6, 7],
       [7, 6, 6, 5],
       [8, 2, 7, 1]])

In [27]:
#Numpy string function

In [31]:
arr = np.array(["pw","skills"])

In [32]:
arr

array(['pw', 'skills'], dtype='<U6')

In [33]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [35]:
np.char.upper(np.array(["Sumit"]))

array(['SUMIT'], dtype='<U5')

In [36]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [38]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [39]:
np.sign(arr1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
np.sin(arr1)

array([[-0.2794155 ,  0.84147098, -0.2794155 ,  0.6569866 ],
       [ 0.6569866 , -0.2794155 , -0.2794155 , -0.95892427],
       [ 0.98935825,  0.90929743,  0.6569866 ,  0.84147098]])

In [41]:
np.log(arr2)

array([[1.09861229, 1.60943791, 1.09861229, 1.38629436],
       [0.        , 1.79175947, 1.60943791, 1.60943791],
       [1.79175947, 0.69314718, 0.69314718, 0.69314718]])

In [42]:
np.power(arr1,2)

array([[36,  1, 36, 49],
       [49, 36, 36, 25],
       [64,  4, 49,  1]])

In [43]:
np.max(arr2)

6

In [44]:
np.std(arr1) #Std deviation

2.3392781412696997

In [45]:
np.var(arr1)

5.472222222222221

In [46]:
np.subtract(arr1,arr2)

array([[ 3, -4,  3,  3],
       [ 6,  0,  1,  0],
       [ 2,  0,  5, -1]])

In [47]:
arr1-arr2

array([[ 3, -4,  3,  3],
       [ 6,  0,  1,  0],
       [ 2,  0,  5, -1]])

In [48]:
np.multiply(arr1,arr2)

array([[18,  5, 18, 28],
       [ 7, 36, 30, 25],
       [48,  4, 14,  2]])

In [49]:
arr1*arr2

array([[18,  5, 18, 28],
       [ 7, 36, 30, 25],
       [48,  4, 14,  2]])

In [53]:
np.mod(arr1,arr2)#Return element wise remaiader

array([[0, 1, 0, 3],
       [0, 0, 1, 0],
       [2, 0, 1, 1]])

In [52]:
np.power(arr1,arr2)

array([[   216,      1,    216,   2401],
       [     7,  46656,   7776,   3125],
       [262144,      4,     49,      1]])

In [54]:
np.mean(arr2)

3.6666666666666665

In [55]:
#sort & search

In [56]:
arr = np.array([5,6,1,2])

In [57]:
arr

array([5, 6, 1, 2])

In [58]:
np.sort(arr1)

array([1, 2, 5, 6])

In [60]:
np.searchsorted(arr, 3)

4

In [61]:
arr

array([5, 6, 1, 2])

In [62]:
arr1 = np.array([0,1,2,3,0,4])

In [63]:
np.count_nonzero(arr1)

4

In [64]:
np.where(arr1>0)

(array([1, 2, 3, 5]),)

In [66]:
np.extract(arr1>0,arr1)

array([1, 2, 3, 4])

In [67]:
np.extract(arr1>2,arr1)


array([3, 4])

In [68]:
arr1

array([0, 1, 2, 3, 0, 4])

In [69]:
arr2

array([[3, 5, 3, 4],
       [1, 6, 5, 5],
       [6, 2, 2, 2]])

In [71]:
np.sort(arr2,axis= 0)

array([[1, 2, 2, 2],
       [3, 5, 3, 4],
       [6, 6, 5, 5]])

In [72]:
np.sort(arr2,axis= 1)

array([[3, 3, 4, 5],
       [1, 5, 5, 6],
       [2, 2, 2, 6]])

In [73]:
np.sort(arr2,axis= 1)

SyntaxError: keyword argument repeated: axis (<ipython-input-73-cd2197a11cdc>, line 1)

In [74]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

In [75]:
#Matrix >> 2d array
import numpy.matlib as nm

In [76]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [77]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
#Numpy Linear Alzebra

In [79]:
arr1

array([0, 1, 2, 3, 0, 4])

In [80]:
arr1

array([0, 1, 2, 3, 0, 4])

In [82]:
arr1

array([[4, 6, 1, 9],
       [8, 5, 3, 7],
       [9, 9, 4, 5]])

In [83]:
arr2

array([[2, 6, 9, 1],
       [3, 6, 9, 8],
       [6, 5, 7, 9]])

In [86]:
#Binary opeartion on array
arr3 = np.random.randint(1, 10,(3,4))
arr4 = np.random.randint(1, 10,(3,4))

In [88]:
arr3 = np.array([[2,3],[4,5]])
arr4 = np.array([[1,3],[4,5]])

In [89]:
arr3 @ arr4

array([[14, 21],
       [24, 37]])

In [90]:
arr3

array([[2, 3],
       [4, 5]])

In [91]:
arr4

array([[1, 3],
       [4, 5]])

In [93]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [94]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [96]:
b = np.array([16, -8, 0])

In [97]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [99]:
np.linalg.det(arr3)

-2.0

In [100]:
np.linalg.inv(arr3)

array([[-2.5,  1.5],
       [ 2. , -1. ]])