In [3]:
import numpy as np
l = [1,2,3,4,5]


In [4]:
arr = np.array(l)

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
np.__version__

'1.23.5'

In [10]:
l = [1,2,3,4,5, "Sumit"]

In [11]:
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Sumit'], dtype='<U21')

In [14]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
type(arr1)

numpy.ndarray

In [17]:
arr1.ndim

2

In [18]:
type(arr1.ndim)

int

In [19]:
l = [1,2,3,4]

In [20]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [22]:
type(np.matrix(l))

numpy.matrix

In [23]:
l.matrix

AttributeError: 'list' object has no attribute 'matrix'

In [25]:
np.matrix([[[1,2],[3,4],[7,8]]])

ValueError: matrix must be 2-dimensional

In [26]:
np.array([[[1,2],[3,4],[7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [27]:
 #more way to convert list to array
np.asarray([[[1,2],[3,4],[7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [28]:
np.asanyarray([[[1,2],[3,4],[7,8]]])

array([[[1, 2],
        [3, 4],
        [7, 8]]])

In [38]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4]])

In [33]:
t = ([1,2,3],[4,5,6])

In [34]:
type(t)

tuple

In [35]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a = 5 
np.array(a)

array(5)

In [39]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [40]:
arr[3]

4

In [41]:
a = arr

In [42]:
a

array([1, 2, 3, 4, 5])

In [43]:
a[0]= 1000

In [44]:
a

array([1000,    2,    3,    4,    5])

In [45]:
arr

array([1000,    2,    3,    4,    5])

In [46]:
arr[3]= 2000

In [47]:
arr

array([1000,    2,    3, 2000,    5])

In [48]:
a

array([1000,    2,    3, 2000,    5])

In [49]:
#there are multiple ways to generating arrays

In [50]:
np.fromfunction(lambda i,j : i==j, shape =(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr.shape

(5,)

In [54]:
arr1.shape

(2, 3)

In [55]:
arr

array([1000,    2,    3, 2000,    5])

In [57]:
arr.size

5

In [58]:
arr1.size

6

In [59]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [62]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
range(5)

range(0, 5)

In [66]:
for i in range(5):
    print(i)

0
1
2
3
4


In [67]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [68]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [69]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7efaf1d80740>

In [72]:
iterable= (i*i for i in range(5))

In [73]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [78]:
np.fromstring('Sumit,Kumar', sep = ',')

/tmp/ipykernel_87/1690226361.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Sumit,Kumar', sep = ',')


array([], dtype=float64)

In [79]:
np.fromiter(iterable, int)

array([], dtype=int64)

In [80]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [81]:
arr.dtype

dtype('int64')

In [82]:
l = [1,2,3]
arr = np.array(l)
arr.dtype

dtype('int64')

In [83]:
l = [1,2,3, "Sumit"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [84]:
#U21 is string data type

In [85]:
list(range(5))

[0, 1, 2, 3, 4]

In [86]:
range(5)

range(0, 5)

In [87]:
range(6)

range(0, 6)

In [88]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [91]:
list(range(1.0,2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [94]:
np.arange(0.1, 10.2 , 0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1])

In [95]:
np.arange(0.1, 10.2 , 0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [96]:
list(np.arange(0.1, 10.2 , 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [97]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [99]:
list(np.linspace(1,5, 20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [103]:
np.logspace(1, 5, 5,  base =2)

array([ 2.,  4.,  8., 16., 32.])

In [104]:
np.logspace(0, 5, 5,  base =2)

array([ 1.        ,  2.37841423,  5.65685425, 13.45434264, 32.        ])

In [105]:
np.logspace(1, 5, 5,  base =8)

array([8.0000e+00, 6.4000e+01, 5.1200e+02, 4.0960e+03, 3.2768e+04])

In [106]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
arr1 = np.zeros(5)

In [111]:
arr1

array([0., 0., 0., 0., 0.])

In [112]:
arr1.shape

(5,)

In [113]:
arr2 = np.zeros((3,4))
arr2.shape

(3, 4)

In [114]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
arr2.ndim

2

In [116]:
arr

array(['1', '2', '3', 'Sumit'], dtype='<U21')

In [117]:
arr3 = np.zeros((3,4,5))
arr3.shape

(3, 4, 5)

In [118]:
arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [119]:
arr3.ndim

3

In [120]:
arr4 = np.zeros((3,4,5,3))
arr4.shape

(3, 4, 5, 3)

In [121]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [122]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [123]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
arr5 = np.ones((3,5))

In [126]:
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
arr5+4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])